"""add game venue_name and is_neutral_site

Revision ID: b796306930f9
Revises: b7e42c9d1a05
Create Date: 2026-09-08 19:17:19.182232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b796306930f9'
down_revision: Union[str, Sequence[str], None] = 'b7e42c9d1a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('venue_name', sa.String(length=120), nullable=True))
    op.add_column('games', sa.Column('is_neutral_site', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_neutral_site')
    op.drop_column('games', 'venue_name')
    # ### end Alembic commands ###
